package ru.kuramov.model;
// Generated 13.12.2016 10:23:28 by Hibernate Tools 5.2.0.Beta1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Article generated by hbm2java
 */
@Entity
@Table(name="Article", catalog="Catalog_IDEA")
public class Article  implements java.io.Serializable {

     private Integer idArticle;
     private Section section;
     private String title;

    public Article() {
    }

	
    public Article(Section section) {
        this.section = section;
    }
    public Article(Section section, String title) {
       this.section = section;
       this.title = title;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idArticle", unique=true, nullable=false)
    public Integer getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(Integer idArticle) {
        this.idArticle = idArticle;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Section_idSection", nullable=false)
    public Section getSection() {
        return this.section;
    }

    public void setSection(Section section) {
        this.section = section;
    }

    
    @Column(name="title", length=150)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

}


