package ru.kuramov.model;
// Generated 13.12.2016 10:23:28 by Hibernate Tools 5.2.0.Beta1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Catalog generated by hbm2java
 */
@Entity
@Table(name="Catalog", catalog="Catalog_IDEA")
public class Catalog  implements java.io.Serializable {

    private Integer idCatalog;
    private String jornal;
    private Set<Edition> editions = new HashSet<Edition>(0);

    public Catalog() {
    }

    public Catalog(String jornal, Set<Edition> editions) {
       this.jornal = jornal;
       this.editions = editions;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idCatalog", unique=true, nullable=false)
    public Integer getIdCatalog() {
        return this.idCatalog;
    }

    public void setIdCatalog(Integer idCatalog) {
        this.idCatalog = idCatalog;
    }

    
    @Column(name="jornal", length=100)
    public String getJornal() {
        return this.jornal;
    }
    
    public void setJornal(String jornal) {
        this.jornal = jornal;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="catalog")
    public Set<Edition> getEditions() {
        return this.editions;
    }
    
    public void setEditions(Set<Edition> editions) {
        this.editions = editions;
    }

}


