package ru.kuramov.model;
// Generated 13.12.2016 10:23:28 by Hibernate Tools 5.2.0.Beta1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edition generated by hbm2java
 */
@Entity
@Table(name="Edition", catalog="Catalog_IDEA")
public class Edition  implements java.io.Serializable {


    private Integer idEdition;
    private Catalog catalog;
    private String edition;
    private Set<Section> sections = new HashSet<Section>(0);

    public Edition() {
    }

    public Edition(Catalog catalog) {
        this.catalog = catalog;
    }
    public Edition(Catalog catalog, String edition, Set<Section> sections) {
       this.catalog = catalog;
       this.edition = edition;
       this.sections = sections;
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idEdition", unique=true, nullable=false)
    public Integer getIdEdition() {
        return this.idEdition;
    }
    
    public void setIdEdition(Integer idEdition) {
        this.idEdition = idEdition;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Catalog_idCatalog", nullable=false)
    public Catalog getCatalog() {
        return this.catalog;
    }

    public void setCatalog(Catalog catalog) {
        this.catalog = catalog;
    }

    
    @Column(name="edition", length=100)
    public String getEdition() {
        return this.edition;
    }
    
    public void setEdition(String edition) {
        this.edition = edition;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="edition")
    public Set<Section> getSections() {
        return this.sections;
    }

    public void setSections(Set<Section> sections) {
        this.sections = sections;
    }

}


